name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

env:
  PROJECT_TYPE: TOOL

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: brew install create-dmg
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: 1
          HOMEBREW_NO_AUTO_UPDATE: 1

      - name: CI Bootstrap
        run: |
          src=$(/usr/bin/curl -Lfs https://raw.githubusercontent.com/acidanthera/ocbuild/master/ci-bootstrap.sh) && eval "$src" || exit 1
          /usr/bin/curl -OL "https://github.com/acidanthera/ocbuild/raw/master/codesign/appsign.sh" || exit 1
          chmod a+x appsign.sh || exit 1

      - name: Compile with codesign (DEBUG)
        if: github.repository_owner == 'vit9696' && github.event_name != 'pull_request'
        env:
          MAC_CERTIFICATE_PASSWORD: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}
          MAC_ACCOUNT_NAME: ${{ secrets.MAC_ACCOUNT_NAME }}
          MAC_ACCOUNT_PASSWORD: ${{ secrets.MAC_ACCOUNT_PASSWORD }}
        run: DEPLOY_SCRIPT="$(pwd)/appsign.sh" xcodebuild -jobs 1 -configuration Debug -scheme 'iChm (Debug)' -derivedDataPath build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Compile with codesign (RELEASE)
        if: github.repository_owner == 'vit9696' && github.event_name != 'pull_request'
        env:
          MAC_CERTIFICATE_PASSWORD: ${{ secrets.MAC_CERTIFICATE_PASSWORD }}
          MAC_ACCOUNT_NAME: ${{ secrets.MAC_ACCOUNT_NAME }}
          MAC_ACCOUNT_PASSWORD: ${{ secrets.MAC_ACCOUNT_PASSWORD }}
        run: DEPLOY_SCRIPT="$(pwd)/appsign.sh" xcodebuild -jobs 1 -configuration Release -scheme 'iChm (Release)' -derivedDataPath build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Compile (DEBUG)
        if: github.repository_owner != 'vit9696' || github.event_name == 'pull_request'
        run: xcodebuild -jobs 1 -configuration Debug -scheme 'iChm (Debug)' -derivedDataPath build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Compile (RELEASE)
        if: github.repository_owner != 'vit9696' || github.event_name == 'pull_request'
        run: xcodebuild -jobs 1 -configuration Release -scheme 'iChm (Release)' -derivedDataPath build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

      - name: Upload to Artifacts
        if: github.repository_owner == 'vit9696' && github.event_name != 'pull_request'
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/Build/Products/*/*.dmg

      - name: Upload to Release
        if: github.event_name == 'release' && github.repository_owner == 'vit9696'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/Build/Products/*/*.dmg
          tag: ${{ github.ref }}
          file_glob: true
